In [2]:
import numpy as np

print("Практична робота №1")
print("Варіант 5 — Дніпро")
print("Михальчук Юліан, ІТ-42")
print("NumPy:", np.__version__)

Практична робота №1
Варіант 5 — Дніпро
Михальчук Юліан, ІТ-42
NumPy: 2.1.3


In [3]:
# Завдання 1

temps = np.array([-4, -3, 3, 11, 17, 21, 23, 22, 16, 9, 3, -2])

print("Температури за 12 місяців:")
print(temps)

print("Кількість місяців:", temps.size)
print("Тип даних:", temps.dtype)
print("Розмірність:", temps.shape)

Температури за 12 місяців:
[-4 -3  3 11 17 21 23 22 16  9  3 -2]
Кількість місяців: 12
Тип даних: int64
Розмірність: (12,)


In [4]:
# Завдання 2

print("Середня температура:", np.mean(temps))
print("Мінімальна температура:", np.min(temps))
print("Максимальна температура:", np.max(temps))
print("Медіана:", np.median(temps))
print("Стандартне відхилення:", np.std(temps))


Середня температура: 9.666666666666666
Мінімальна температура: -4
Максимальна температура: 23
Медіана: 10.0
Стандартне відхилення: 9.689627902499089


In [5]:
# Завдання 3

print("Температури вище 15°C:")
print(temps[temps > 15])

print("Кількість місяців з температурою вище 15°C:")
print(np.sum(temps > 15))

print("Місяці з від'ємною температурою:")
print(temps[temps < 0])

Температури вище 15°C:
[17 21 23 22 16]
Кількість місяців з температурою вище 15°C:
5
Місяці з від'ємною температурою:
[-4 -3 -2]


In [6]:
# Завдання 4

# Перетворення температур із °C у °F
temps_f = temps * 9 / 5 + 32

print("Температури у °C:")
print(temps)

print("Температури у °F:")
print(temps_f)

Температури у °C:
[-4 -3  3 11 17 21 23 22 16  9  3 -2]
Температури у °F:
[24.8 26.6 37.4 51.8 62.6 69.8 73.4 71.6 60.8 48.2 37.4 28.4]


In [7]:
# Завдання 4. Двовимірний масив і axis

days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])

# Умовна кількість сонячних годин за місяць
sunny_hours = np.array([60, 80, 120, 170, 230, 260, 290, 270, 200, 140, 70, 50])

data = np.array([temps, days_in_month, sunny_hours])

print("Форма масиву:", data.shape)
print("\nМасив:")
print(data)

print("\nСума по кожному рядку:")
print(data.sum(axis=1))

print("\nСереднє по кожному рядку:")
print(data.mean(axis=1))

print("\nСума по кожному стовпцю:")
print(data.sum(axis=0))

print("\nДля січня сума =", data.sum(axis=0)[0])
print("Це сума температури, кількості днів і умовних сонячних годин за січень.")

Форма масиву: (3, 12)

Масив:
[[ -4  -3   3  11  17  21  23  22  16   9   3  -2]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 60  80 120 170 230 260 290 270 200 140  70  50]]

Сума по кожному рядку:
[ 116  365 1940]

Середнє по кожному рядку:
[  9.66666667  30.41666667 161.66666667]

Сума по кожному стовпцю:
[ 87 105 154 211 278 311 344 323 246 180 103  79]

Для січня сума = 87
Це сума температури, кількості днів і умовних сонячних годин за січень.


In [8]:
# Завдання 5. Збереження та завантаження масиву

np.save("dnipro_temps.npy", temps)

loaded_temps = np.load("dnipro_temps.npy")

print("Завантажені дані:")
print(loaded_temps)

print("Масиви однакові:", np.array_equal(temps, loaded_temps))

Завантажені дані:
[-4 -3  3 11 17 21 23 22 16  9  3 -2]
Масиви однакові: True


In [9]:
# Завдання 1. Створення масивів

# Варіант 5 — Дніпро
temps = np.array([-4, -3, 3, 11, 17, 21, 23, 22, 16, 9, 3, -2])

print("Температури Дніпра:")
print(temps)

print("Тип:", temps.dtype)
print("Форма:", temps.shape)
print("Кількість елементів:", temps.size)
print("Кількість вимірів:", temps.ndim)

Температури Дніпра:
[-4 -3  3 11 17 21 23 22 16  9  3 -2]
Тип: int64
Форма: (12,)
Кількість елементів: 12
Кількість вимірів: 1


In [10]:
# Завдання 2. Векторизовані обчислення

days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])
month_numbers = np.arange(1, 13)

temps_f = temps * 9 / 5 + 32

warm_days = days_in_month[temps > 15].sum()

print("Температури у °F:")
print(temps_f)

print("Кількість днів з температурою вище 15°C:", warm_days)

print("Кількість днів у році:", days_in_month.sum())
print("Перевірка 365 днів:", days_in_month.sum() == 365)

Температури у °F:
[24.8 26.6 37.4 51.8 62.6 69.8 73.4 71.6 60.8 48.2 37.4 28.4]
Кількість днів з температурою вище 15°C: 153
Кількість днів у році: 365
Перевірка 365 днів: True


In [11]:
# Завдання 3. Індексація і фільтрація

max_index = temps.argmax()
min_index = temps.argmin()

print("Найтепліший місяць:")
print("Температура:", temps[max_index], "°C")
print("Номер місяця:", month_numbers[max_index])
print("Індекс:", max_index)

print("\nНайхолодніший місяць:")
print("Температура:", temps[min_index], "°C")
print("Номер місяця:", month_numbers[min_index])
print("Індекс:", min_index)

print("\nМісяці з температурою нижче 0°C:")
print(month_numbers[temps < 0])

print("\nТемператури за зростанням:")
print(np.sort(temps))

print("\nОригінальний масив:")
print(temps)


Найтепліший місяць:
Температура: 23 °C
Номер місяця: 7
Індекс: 6

Найхолодніший місяць:
Температура: -4 °C
Номер місяця: 1
Індекс: 0

Місяці з температурою нижче 0°C:
[ 1  2 12]

Температури за зростанням:
[-4 -3 -2  3  3  9 11 16 17 21 22 23]

Оригінальний масив:
[-4 -3  3 11 17 21 23 22 16  9  3 -2]


In [12]:
# Завдання 5. reshape і broadcasting

rows = np.array([temps, days_in_month])
correction = np.array([1, 0])

print("Форма rows:", rows.shape)
print("Форма correction:", correction.shape)

# Спроба додавання без reshape
try:
    result_error = rows + correction
except ValueError as e:
    print("\nПомилка при rows + correction:")
    print(e)

# Змінюємо форму correction з (2,) на (2, 1)
correction_reshaped = correction.reshape(2, 1)

print("\nНова форма correction:", correction_reshaped.shape)

result = rows + correction_reshaped

print("\nРезультат після broadcasting:")
print(result)

Форма rows: (2, 12)
Форма correction: (2,)

Помилка при rows + correction:
operands could not be broadcast together with shapes (2,12) (2,) 

Нова форма correction: (2, 1)

Результат після broadcasting:
[[-3 -2  4 12 18 22 24 23 17 10  4 -1]
 [31 28 31 30 31 30 31 31 30 31 30 31]]


## Відповіді на питання

**1. Яка різниця між shape == (12,) і shape == (1, 12)?**  
(12,) — це одновимірний масив із 12 елементів.  
(1, 12) — це двовимірний масив з одним рядком і 12 стовпцями.

**2. Чому temps[temps > 15] має іншу довжину, ніж temps?**  
Тому що булева індексація залишає тільки ті елементи масиву, які задовольняють умову temps > 15.

**3. Що станеться при додаванні масиву форми (3,) до масиву форми (3, 12)?**  
Виникне помилка broadcasting, оскільки останні виміри 3 і 12 несумісні.

**4. Чому rows + correction дає помилку, а rows + correction.reshape(2, 1) — ні?**  
rows має форму (2, 12), а correction — (2,), тому виміри 12 і 2 несумісні. Після reshape correction має форму (2, 1). Розмір 1 може розширитися до 12, тому broadcasting працює і кожна поправка додається до відповідного рядка.

In [13]:
# Завдання 1. Створення масивів — фінальна версія

# Варіант 5 — Дніпро
temps = np.array([-4, -3, 3, 11, 17, 21, 23, 22, 16, 9, 3, -2])

# Кількість днів у місяцях невисокосного року
days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])

# Номери місяців від 1 до 12
month_numbers = np.arange(1, 13)

print("temps:", temps)
print("shape:", temps.shape, "dtype:", temps.dtype)

print("\ndays_in_month:", days_in_month)
print("shape:", days_in_month.shape, "dtype:", days_in_month.dtype)

print("\nmonth_numbers:", month_numbers)
print("shape:", month_numbers.shape, "dtype:", month_numbers.dtype)

temps: [-4 -3  3 11 17 21 23 22 16  9  3 -2]
shape: (12,) dtype: int64

days_in_month: [31 28 31 30 31 30 31 31 30 31 30 31]
shape: (12,) dtype: int64

month_numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,) dtype: int64
